name: Auto Update Submodules

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule update --remote
          git add .

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Commit changes if any
        run: |
          git diff --cached --quiet || git commit -m "chore: auto-update submodules"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

